// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/example-protofiles/example_2.proto

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Test3 struct {
	Type2                *int32   `protobuf:"varint,2,req,name=type2" json:"type2,omitempty"`
	Label2               *string  `protobuf:"bytes,1,req,name=label2" json:"label2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test3) Reset()         { *m = Test3{} }
func (m *Test3) String() string { return proto.CompactTextString(m) }
func (*Test3) ProtoMessage()    {}
func (*Test3) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_2_b81f5ea06d4dc084, []int{0}
}
func (m *Test3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test3.Unmarshal(m, b)
}
func (m *Test3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test3.Marshal(b, m, deterministic)
}
func (dst *Test3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test3.Merge(dst, src)
}
func (m *Test3) XXX_Size() int {
	return xxx_messageInfo_Test3.Size(m)
}
func (m *Test3) XXX_DiscardUnknown() {
	xxx_messageInfo_Test3.DiscardUnknown(m)
}

var xxx_messageInfo_Test3 proto.InternalMessageInfo

func (m *Test3) GetType2() int32 {
	if m != nil && m.Type2 != nil {
		return *m.Type2
	}
	return 0
}

func (m *Test3) GetLabel2() string {
	if m != nil && m.Label2 != nil {
		return *m.Label2
	}
	return ""
}

func init() {
	proto.RegisterType((*Test3)(nil), "example.Test3")
}

func init() {
	proto.RegisterFile("pkg/example-protofiles/example_2.proto", fileDescriptor_example_2_b81f5ea06d4dc084)
}

var fileDescriptor_example_2_b81f5ea06d4dc084 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0xc8, 0x4e, 0xd7,
	0x4f, 0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xcb, 0xcc,
	0x49, 0x2d, 0x86, 0x09, 0xc5, 0x1b, 0xe9, 0x81, 0x05, 0x85, 0xd8, 0xa1, 0x02, 0x4a, 0xa6, 0x5c,
	0xac, 0x21, 0xa9, 0xc5, 0x25, 0xc6, 0x42, 0x22, 0x5c, 0xac, 0x25, 0x95, 0x05, 0xa9, 0x46, 0x12,
	0x4c, 0x0a, 0x4c, 0x1a, 0xac, 0x41, 0x10, 0x8e, 0x90, 0x18, 0x17, 0x5b, 0x4e, 0x62, 0x52, 0x6a,
	0x8e, 0x91, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x67, 0x10, 0x94, 0x07, 0x08, 0x00, 0x00, 0xff, 0xff,
	0x9e, 0xc5, 0x0d, 0xf4, 0x68, 0x00, 0x00, 0x00,
}
